InitiatorMethionineBehavior = "Variable"
MaxMissedCleavages = 2
ConserveMemory = true
MinPeptideLength = 5
MaxModificationIsoforms = 4096
Protease = "trypsin"
BIons = true
YIons = true
ZdotIons = false
CIons = false
ProductMassTolerance = "±0.0100 Absolute"
PrecursorMassTolerance = "±10.0000 PPM"
NonLinearCalibration = true
WriteIntermediateFiles = false
ScoreCutoff = 5.0
MaxDegreeOfParallelism = -1
LocalizeAll = true
ListOfModsFixed = "Common Fixed\tCarbamidomethyl of C"
ListOfModsVariable = "Common Variable\tOxidation of M"
ListOfModsLocalize = ""
TaskType = "Calibrate"
DoPrecursorDeconvolution = true
UseProvidedPrecursorInfo = true
DeconvolutionIntensityRatio = 4.0
DeconvolutionMaxAssumedChargeState = 10
DeconvolutionMassTolerance = "±5.0000 PPM"

[commonParameters]
MaxDegreeOfParallelism = 1
LocalizeAll = true
ListOfModsFixed = "Common Fixed\tCarbamidomethyl of C"
ListOfModsVariable = "Common Variable\tOxidation of M"
ListOfModsLocalize = ""
DoPrecursorDeconvolution = true
UseProvidedPrecursorInfo = true
DeconvolutionIntensityRatio = 4.0
DeconvolutionMaxAssumedChargeState = 10
DeconvolutionMassTolerance = "±5.0000 PPM"
InitiatorMethionineBehavior = "Variable"
MaxMissedCleavages = 2
MinPeptideLength = 5
MaxModificationIsoforms = 4096
TotalPartitions = 1
Protease = "trypsin"
BIons = true
YIons = true
ZdotIons = false
CIons = false
ProductMassTolerance = "±0.0100 Absolute"
ConserveMemory = true
ScoreCutoff = 5.0
