ListOfModListsFixed = ["Mods\\f.txt"]
ListOfModListsVariable = ["Mods\\v.txt"]
ListOfModListsLocalize = ["Mods\\ptmlist.txt"]
ProductMassTolerance = "±0.01 Absolute"
ClassicSearch = true
DoParsimony = false
NoOneHitWonders = true
Quantify = false
QuantifyRtTol = 77.0
QuantifyPpmTol = 77.0
DoHistogramAnalysis = true
SearchDecoy = true
SearchModes = ["10ppmAroundZero ppmAroundZero 10"]
ConserveMemory = false
TaskType = "Search"
InitiatorMethionineBehavior = "Cleave"
MaxMissedCleavages = 2
MaxModificationIsoforms = 4096
Protease = "trypsin"
BIons = true
YIons = true
ZdotIons = false
CIons = false
